default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: circleci_dev

production:
  <<: *default
  database: circleci_prod

test:
  <<: *default
  database: circleci_test